.gitignore, internal/partitions/partition.go, internal/partitions/partition_test.go, internal/verifier/check.go, internal/verifier/migration_verifier.go, internal/verifier/migration_verifier_test.go, internal/verifier/verification_task.go, main/migration_verifier.go
Added `globalFilter` field to the Verifier for user-defined filter. The filter is applied when fetching documents.
=> REP-2942 Verifier: Add user-defined query filtering to the initial check logic

README.md, internal/partitions/partition.go, internal/partitions/partition_test.go, internal/verifier/check.go, internal/verifier/migration_verifier.go, internal/verifier/migration_verifier_test.go, internal/verifier/web_server.go, internal/verifier/web_server_test.go
The `/check` endpoint takes a JSON filter. The verifier parses the JSON filter to `map[string]any`. The verifier starts a change stream without query filtering. The verifier generates a recheck document for a change event of a filtered document, but the document should be filtered out during fetching and thus not compared by the verifier.
=> REP-2943 / REP-2944: Add `filter` parameter to `/check` endpoint and enable query filtering 

internal/partitions/partitions.go, internal/util/error.go, internal/verifier/migration_verifier.go
This PR adds `Location28799` error and make it retryable if running a pipeline with `$sample` stage.
=> REP-3423 Migration-verifier should retry on Location28799 error while sampling documents

internal/partitions/partitions.go, internal/verifier/migration_verifier.go, internal/verifier/migration_verifier_test.go
This PR adds a filter to the partition logic so that partition bounds are created by randomly sampling filtered documents. Number of partitions is calculated by multiplying a ratio of filtered documents with the entire-collection num of partitions. Since sampling of partition bounds will use filtered documents, they will be more evenly distributed across partitions. A more reasonable number of partitions will also be created if only a small subset of documents out of a collection are to be included in the filter. If the partitioning-after-filtering approach takes too long (timeout error), it will fall back to partitioning without filtering.
=> REP-3431 Create partitions using _ids of filtered documents 

internal/verifier/migration_verifier.go, internal/verifier/summary.go, internal/verifier/verification_task.go
It’s been common with the verifier for generation 0’s report to indicate “Mismatches found” but to show 0 documents that actually do mismatch. This changeset fixes that; specifically:
- UpdateVerificationTask() now persists the task’s Ids.
- ProcessVerifyTask() now populates Ids and FailedDocs as reportDocumentMismatches() expects.
Additionally, some comments are added to aid future maintenance, a few “unhelpful” iteration variables are renamed, and the leftover “Type” column header in the mismatched-documents table is removed.
=> REP-2682 Fix failure report with no shown failures.

internal/partitions/partitions.go, internal/retry/retry.go, internal/retry/retryer_test.go
In v5.0, the error "collectionUUID is not supported on a mongos" in the collstats command is not retried because the error is a "FailedToParse" error. I added the retry condition for the collectionUUID error in v5.0.
=> REP-4197: fix collectionUUID not supported error for 5.0 versions

main/migration_verifier.go
PR #13 added a `configFile` parameter. That changeset errantly made that parameter compulsory. This fixes that so that `--configFile` is optional, as we want.
=> REP-4299 Make `configFile` optional.

internal/verifier/migration_verifier.go, internal/verifier/migration_verifier_test.go
Previously we’d show messages like `Mismatch : src: 0xc0a8a7ca7e` when index properties mismatched. This fixes that.
=> REP-2460 Dereference pointers when showing index discrepancies.

README.md, internal/verifier/migration_verifier.go, main/migration_verifier.go
We have seen issues with nearest read preference (e.g. [REP-4294](https://jira.mongodb.org/browse/REP-4294), [SERVER-87673](https://jira.mongodb.org/browse/SERVER-87673)). The defensive thing to do will be to set primary read pref by enforcing usage of primary read preference in the verifier.
=> REP-4496: Legacy migration-verifer should use primary readpref

.gitignore, internal/verifier/change_stream.go, internal/verifier/list_namespaces.go, internal/verifier/migration_verifier_test.go, internal/verifier/verification_task.go, precious.toml
This also includes some linting fixes and some tooling updates.
=> REP-4790 Exclude all Mongosync internal DBs, including those used by the embedded verifier

internal/documentmap/documentmap.go
Generation 0 heap pprof file has shown high memory usage by the `ImportFromCursor` function itself. This PR attempts to improve the memory usage of the migration verifier by:
- removing an extra BSON decode step before storing a document to a doc map in `ImportFromCursor`
- using a byte buffer when constructing map keys in `getMapKey`
=> Reduce memory usage of the migration verifier

internal/logger/logger.go
`mongosync.log` is an unideal log file name for migration-verifier. :)
=> Fix log file name.

internal/verifier/change_stream.go
PR #30 added persistence of the change stream’s resume token but mishandled some of the refactoring by making every change stream iteration loop read all events.
This restores the intended logic: check for context cancellation or the end of the change stream after each event.
=> REP-5201 Fix change stream iteration.

internal/verifier/change_stream.go, internal/verifier/check.go, internal/verifier/migration_verifier_test.go
REVIEWER NOTE: I suggest reviewing individual commits. (I’m going to merge them as such rather than squashing.)
This applies a few small fixes to the change stream’s error handling and improves logging to facilitate easier diagnosis when tests fail.
=> Change stream fixes & log improvements.

internal/verifier/change_stream.go, internal/verifier/recheck.go
We receive events and enqueue rechecks in the same thread. When there are 1,000s of rechecks to enqueue at once, though, we need faster throughput than a single thread will allow.
This changeset fixes that by parallelizing the enqueueing of rechecks.
=> REP-5277 Parallelize persistence of rechecks.

internal/verifier/change_stream.go, internal/verifier/recheck_test.go
Previously all change events’ document sizes were recorded “pessimistically” as 16 MiB. This helped to avoid OOMs. It came at a cost, though: when the recheck queue is converted to recheck tasks, those tasks are sized so as to approximate the configured partition size. Thus, if the partition size was 400 MiB (the default), only 25 change events could fit into a recheck task. If there are 250,000 pending rechecks—not unfeasible for a large, busy data set after generation 0—that’s 10,000 tasks to create and perform, which is inefficient.
PR #34 all but eliminates the OOMs, which undercuts that “pessimism”’s benefit. It makes more sense now to allow for the possibility of large recheck tasks in order to minimize the number of tasks. Moreover, we can get pretty good confidence about document …
=> REP-5283 Report change event document sizes accurately.

internal/verifier/check.go, internal/verifier/migration_verifier.go
This changeset improves several logs by:
- reporting their data points as structured data rather than phrase components
- including the task ID (“PrimaryKey” in code) to facilitate correlation among logs and metadata
- adding a few other data points and adding new log events such as task-finished
=> Improve logging statements’ accuracy and reporting of data points.

internal/verifier/compare.go, internal/verifier/unit_test_util.go
PR #34 errantly omitted some error checks. This changeset restores those.
=> REP-5230 Fix missing error checks.

internal/reportutils/reportutils.go, internal/verifier/recheck.go, internal/verifier/verification_task.go
Presently the only limit on a recheck task’s size is BSON’s document-size limit (i.e., 16 MiB). Thus, a single task can feasibly include every recheck. If there are millions of rechecks, that means only 1 thread is doing all of them, which increases the likelihood that migration-verifier would fail to keep pace with the source workload.
This changeset addresses this problem by capping the recheck task size according to the number of pending rechecks and the number of workers.
=> Ensure parallelization of rechecks by capping recheck task size.

internal/verifier/compare.go
In certain cases reads from the source or destination seem to hang. This changeset makes two changes to address that:
1. A timer is added to detect hung reads. It is hard-coded at 10 minutes, which seems conservative enough.
2. The comparer thread fails immediately if it finds a failure from the source. Previously it would read from the destination if the source failed. (This _could_ be the case of the apparent hangs, but how that could be seems unclear.)
=> Add a timeout when reading cursor, and fail immediately.

internal/verifier/migration_verifier.go, internal/verifier/migration_verifier_test.go, mslices/slices.go, mslices/slices_test.go
When the verifier finds a metadata mismatch it enqueues a recheck of that metadata in the next generation.
This is fine, but since metadata-check tasks also partition documents & create document-checking tasks for those  partitions, what’s been happening is that any time some collection metadata property (e.g., an index) mismatches, tasks are enqueued to recheck all of the collection’s documents.
Since the partitioning stuff is only appropriate for generation 0, this changeset restricts that behavior accordingly.
For convenience this also adds mslices.Of from mongosync’s mongo-go.
=> REP-5319 Only create partition-verification tasks in generation 0.

internal/verifier/migration_verifier.go, internal/verifier/migration_verifier_test.go
This fixes breakage found in mongosync’s testing after REP-5274.
=> REP-5274: Ignore the “background” field in index specifications.

internal/verifier/change_stream_test.go, internal/verifier/check_runner.go, internal/verifier/migration_verifier_test.go
This prevents the test from hanging if the verifier fails for an unforeseen reason.
=> Make CheckRunner methods check to see if the verifier failed.

internal/verifier/change_stream.go, internal/verifier/change_stream_test.go, internal/verifier/migration_verifier_test.go
This prevents one means of triggering a BSONObjectTooLarge error. Such errors could still happen from over-large `_id` fields, but users are unlikely to have them.
Found while running migration-verifier’s change stream against mongosync’s nondeterministic tests.
=> REP-5318 Hide `updateDescription` in update events.

internal/verifier/migration_verifier.go, internal/verifier/migration_verifier_test.go
This adds a $literal around the documents inserted into the $documents aggregation to allow for number-type discrepancies in index specifications. See the test case added here for why this is needed.
=> REP-5330 Fix deep index comparison.

internal/retry/retry.go, internal/retry/retryer_test.go, internal/verifier/change_stream_test.go, internal/verifier/check.go, internal/verifier/clustertime_test.go, internal/verifier/migration_verifier.go, internal/verifier/migration_verifier_test.go, internal/verifier/recheck.go, internal/verifier/recheck_test.go, internal/verifier/reset_test.go, internal/verifier/verification_task.go
While this is a regrettably large changeset, most of it is trivial changes like passing a context where previously the function used context.Background().
The check logic contains most of this PR’s “interesting” changes.
-----
In certain cases migration-verifier would log on fatal errors rather than propagating them back up the call stack. This has led to failures to compare documents that were effectively ignored save for being noted in the log. This changeset fixes that so that such exceptional cases will halt the verification.
Broadly speaking, this changeset:
a) brings idiomatic Context propagation in places where context.Background() was used
b) converts Error() logs and “failed” task statuses to returned errors
As of this changeset, any task in “failed” indicates a mismatch rather …
=> REP-5324 Normalize error handling.

internal/reportutils/reportutils.go, internal/verifier/check.go, internal/verifier/compare.go, internal/verifier/migration_verifier.go, internal/verifier/migration_verifier_test.go
This tweaks the document comparison from REP-5230 (PR #34) so that, instead of reading source and destination documents in series, they are read in parallel. This should improve comparison speed.
This copies syncmap and syncslice from mongosync.
=> Read documents in parallel

internal/partitions/partitions.go, internal/retry/constants.go, internal/retry/error.go, internal/retry/retry.go, internal/retry/retry_info.go, internal/retry/retryer.go, internal/retry/retryer_test.go, internal/util/error.go, internal/uuidutil/get_uuid.go, internal/verifier/change_stream.go, internal/verifier/clustertime.go, internal/verifier/compare.go, internal/verifier/migration_verifier.go, internal/verifier/mongos_refresh.go, internal/verifier/recheck.go
We need retry logic around `find` cursor iteration, but the retryer’s IterationSuccess() method won’t work properly with how we compare partitions document-by-document. If, for example, the source hangs but we call IterationSuccess() on every destination success, we’ll never time out the retries. But we need IterationSuccess() to work or else there are no retries for partitions that take a long time to read.
This changeset fixes that by rewriting the retryer to take multiple callbacks. Each callback now takes a context that the retryer uses to stop the function whenever another thread has failed.
Since migration-verifier doesn’t handle DDL events, there’s no point to handling collection UUIDs. Thus, the initial commits in this PR resolve longstanding technical debt.
This also synchronizes …
=> REP-5329 Teach retryer to run +1 callback in parallel.

internal/partitions/partitions.go, internal/retry/retry.go, internal/retry/retryer.go, internal/uuidutil/get_uuid.go, internal/verifier/compare.go, internal/verifier/mongos_refresh.go
Commit 31cc703daf was broken because it didn’t actually recreate the callbacks as needed to redo the reads.
(Unfortunately there’s little good way to test this directly, but mongosync’s CI testing caught it.)
This changeset fixes that by adding a callback to the retryer that runs at the start of each iteration.
=> REP-5329 Fix retry on document reads.

internal/retry/retry.go, internal/verifier/change_stream_test.go, internal/verifier/check.go, internal/verifier/migration_verifier.go, internal/verifier/migration_verifier_test.go, internal/verifier/recheck.go, internal/verifier/recheck_test.go, internal/verifier/reset_test.go, internal/verifier/summary.go, internal/verifier/verification_task.go
This changeset adds additional error codes to the retryer’s list of transient errors.
It also applies the retryer in several new places:
- metadata prep at the beginning of check
- generation of recheck tasks
- clearing of the recheck queue
- fetching failed & incomplete tasks
- find the next worker task
- get verification status
- inserting a partition verification task
- inserting a recheck task
- updating a verification task
- creating primary task
- setting the primary task to complete
A few functions are renamed for clarity as well, and some function calls are rewritten to read (hopefully) a bit more clearly.
=> REP-5329 Improve retryer & apply it more consistently.

internal/verifier/uri.go
PR #64 introduced a bug where it would try to refresh mongoses regardless of server version.
This fixes that by only refreshing mongoses for pre-v5 server versions.
=> REP-5337 Don’t mongos-refresh on pre-v5 clusters.

.github/workflows/all.yml, README.md, build.sh, main/migration_verifier.go
This will help debugging cases where migration-verifier may have been built from an old revision.
=> Add git revision to migration-verifier.

internal/verifier/change_stream.go, internal/verifier/change_stream_test.go, internal/verifier/integration_test_suite.go, internal/verifier/list_namespaces.go, internal/verifier/migration_verifier_test.go
REVIEWER NOTE: The first couple commits here are general cleanup. This PR will be merged via rebase.
-----
To make migration-verifier’s change stream work with mongosync CI we need to ignore mongosync’s internal databases, which mongosync will manipulate alongside migration-verifier.
This changeset adjusts the change stream logic accordingly.
=> REP-5317 Ignore mongosync DBs on destination.

internal/verifier/compare.go
This should fix a mongosync CI failure where migration-verifier refused to retry.
=> Retry “CursorKilled” when iterating documents.

internal/partitions/partitions.go, internal/retry/retry.go, internal/retry/retry_info.go, internal/retry/retryer.go, internal/retry/retryer_test.go, internal/uuidutil/get_uuid.go, internal/verifier/change_stream.go, internal/verifier/check.go, internal/verifier/clustertime.go, internal/verifier/compare.go, internal/verifier/migration_verifier.go, internal/verifier/mongos_refresh.go, internal/verifier/recheck.go, internal/verifier/verification_task.go, msync/typed_atomic.go, msync/typed_atomic_test.go
This improves the retryer in several ways that should aid in debugging such failures as REP-5358:
- There are now descriptions for each callback and (optionally) the loop itself. Those descriptions go in the relevant log messages.
- NoteSuccess() also takes a description that goes into logs.
- Retried failures are now noted at info level rather than debug.
- The retryer now notes success of a retried operation.
- Long-running operations that go without a success for >1min will be noted in the log as a warning.
- The “retry randomly” functionality is removed. (None of the existing tests use it.)
The above requires a revamp of the retryer interface, so all callers into it are rewritten.
=> REP-5358 Revamp retryer.

internal/verifier/change_stream.go, internal/verifier/summary.go, msync/typed_atomic.go, msync/typed_atomic_test.go
This adds a report of change stream lags to the logs’ progress reports.
=> Add change stream lag to periodic progress reports.

internal/verifier/change_stream.go, internal/verifier/change_stream_test.go
The previous logic was backwards, which caused uint overflow.
This adds a test that usually passes without this change but should occasionally fail. (It should always pass, though, with this change.)
=> Fix change stream lag calculation.

.github/workflows/all.yml, README.md
The disclaimer is now updated with links to the mongosync embedded verifier docs.
=> Update disclaimer and link to mongosync embedded verifier docs

internal/verifier/check.go, internal/verifier/check_runner.go, internal/verifier/generation.go, internal/verifier/recheck_test.go
Previously migration-verifier did not persist its generation, so if it crashed in a generation after generation 0 it would still restart at generation 0.
This could cause any enqueued rechecks not to happen until the restarted verifier reached the prior verifier run’s generation. If the user called `writesOff` before then, though, the rechecks would never happen. Thus, migration-verifier could neglect important rechecks.
This fixes that by persisting migration-verifier’s generation at the start of each generation. Thus, any tasks that need to be rerun, or enqueued rechecks that need to be processed into checks for the next generation, will be replayed in the event of a crash.
=> REP-5550 Add resumability for recheck generations

internal/util/context.go, internal/verifier/change_stream.go, internal/verifier/change_stream_test.go, internal/verifier/check.go, internal/verifier/migration_verifier.go, internal/verifier/migration_verifier_test.go
This fixes a hang that previously happened if migration-verifier received an event that it couldn’t handle.
Specific changes:
- The event optype and namespace presence are checked right after decoding. Previously this happened in the handler, which was the immediate cause of the hang that this changeset fixes. Doing this check makes the failure faster and more prominent.
- If the handler fails, it stores its error, and the reader checks for that error.
- Many debug-level logs are added.
- Context cancellations/timeouts are reported with their Cause.
- WritesOff() is rewritten to make it easier to reason about the mutex handling’s correctness.
- The generation-end error check no longer mistakenly assumes that, if the worker-controller thread finished without error, then all is well.
This …
=> REP-5470 Fix hang when handler thread hits an error.

internal/verifier/mongos_refresh.go, internal/verifier/uri.go
The verbiage around refreshing mongos cache assumed that the cluster was the source. This changeset fixes that so that the verbiage correctly says “source” or “destination”.
This also makes it no longer fatal if the single-host client fails to disconnect.
=> Fix messaging around the destination’s mongos cache refresh.

internal/verifier/migration_verifier.go, internal/verifier/migration_verifier_test.go
Report mismatch details in the case of field-order-sensitive verification:
1. Report mismatched fields if the field content is different.
2. Report different field order if the field content matches but the field order is different.
=> REP-5621 migration-verifier: Report field-order-sensitive mismatch details

internal/verifier/summary.go
This fixes a cosmetic issue in logs where the “Source’s most frequently-changing namespaces” table header appeared apart from the actual table.
=> Fix changing-namespaces table caption in logs.

internal/verifier/compare.go, internal/verifier/migration_verifier_test.go
`compareDocsFromChannels` compares all documents for an entire partition, which can take a while. That function hasn’t been reporting any midway successes, which has caused “Operation has not reported success for a while” warnings while it processes documents. Those warnings could even cause spurious failures.
This changeset fixes that by having it report success when it receives a document.
=> REP-5797 Fix spurious “Operation has not reported success for a while” logs.

internal/types/types.go, internal/util/math.go, internal/verifier/migration_verifier.go, internal/verifier/summary.go
This adds a simple events-per-second computation to the progress logs, which will provide a useful at-a-glance metric of how active the change streams are. It also changes the logic a bit to compute all time deltas from the same “now”.
=> Add events per second to log, and use same “now” in progress logs.

go.mod, go.sum, internal/verifier/change_stream.go, internal/verifier/change_stream_test.go, mstrings/builder.go, vendor/github.com/huandu/go-clone/.gitignore, vendor/github.com/huandu/go-clone/LICENSE, vendor/github.com/huandu/go-clone/README.md, vendor/github.com/huandu/go-clone/allocator.go, vendor/github.com/huandu/go-clone/allocatormethods.go, vendor/github.com/huandu/go-clone/arena.go, vendor/github.com/huandu/go-clone/arena_go120.go, vendor/github.com/huandu/go-clone/atomic_go119.go, vendor/github.com/huandu/go-clone/clone.go, vendor/github.com/huandu/go-clone/cloner.go, vendor/github.com/huandu/go-clone/generic/LICENSE, vendor/github.com/huandu/go-clone/generic/README.md, vendor/github.com/huandu/go-clone/generic/api.go, vendor/github.com/huandu/go-clone/generic/arena.go, vendor/github.com/huandu/go-clone/generic/register.go, vendor/github.com/huandu/go-clone/headers.go, vendor/github.com/huandu/go-clone/interfacedata.go, vendor/github.com/huandu/go-clone/mapiter.go, vendor/github.com/huandu/go-clone/mapiter_go112.go, vendor/github.com/huandu/go-clone/memory.go, vendor/github.com/huandu/go-clone/structtype.go, vendor/github.com/huandu/go-clone/wrapper.go, vendor/modules.txt
When mongosync migrates capped collections it sets the collection limits during commit, which causes the destination to emit `modify` events in its change stream. These have caused migration-verifier to fail because of the “unrecognized” event type.
This changeset alters that logic so that migration-verifier will log `modify` events from the destination and ignore them rather than treating them as fatal.
Additionally, this updates the unknown-event error to include the change event in its bson.Raw form rather than a struct. This ensures that we show the entire event rather than just those parts that we parse.
=> Ignore/log `modify` events on the destination.

.golangci.yml, contextplus/c.go, contextplus/cause_test.go, contextplus/contextplus.go, contextplus/unit_test.go, internal/retry/retry.go, internal/retry/retryer_test.go, internal/util/context.go, internal/verifier/change_stream_test.go, internal/verifier/check.go, internal/verifier/compare.go, internal/verifier/compare_test.go, internal/verifier/integration_test_suite.go, internal/verifier/recheck.go, internal/verifier/web_server.go
```
2025-03-27T08:52:49-04:00 DBG Non-retryable error occurred. error="context canceled" description=["finding next task to do in generation 0"] error code=0
```
^^ The above doesn’t tell us _why_ the context was canceled.
This changeset causes all contexts’ Err() to show their cancellation causes, e.g:
```
2025-03-27T08:52:49-04:00 DBG Non-retryable error occurred. error="context canceled: generation 0 finished" description=["finding next task to do in generation 0"] error code=0
```
Note the addition of `generation 0 finished`, which lets us know why the context was canceled.
=> Migrate to contextplus for more informative “context canceled” errors.

.github/workflows/lint.yml, .golangci.yml, internal/keystring/keystring_decoder.go, internal/partitions/unit_test.go, internal/retry/retryer_test.go, internal/retry/unit_test.go, internal/util/error.go, internal/verifier/bson_compare.go, internal/verifier/change_stream_test.go, internal/verifier/check.go, internal/verifier/integration_test_suite.go, internal/verifier/migration_verifier.go, internal/verifier/migration_verifier_bench_test.go, internal/verifier/summary.go, internal/verifier/verification_task.go, internal/verifier/web_server.go, main/migration_verifier.go
This also renames a couple of internal methods for better clarity, thanks to helpful pointers from the new linter version.
=> Update to golangci-lint v2

internal/util/agg.go, internal/verifier/change_stream.go, internal/verifier/check.go, internal/verifier/list_namespaces.go, mmongo/agg.go
Pure string operations generally outperform regular expressions. This changeset alters the relevant paths accordingly.
During testing it was observed that ListAllUserCollections() (which calls the altered logic) has an unused flag. This changeset removes that flag and renames the function. Related error messaging is also augmented.
=> Filter namespaces by string prefix rather than regexp.

internal/verifier/change_stream_test.go, internal/verifier/check.go, internal/verifier/migration_verifier.go, internal/verifier/migration_verifier_bench_test.go, internal/verifier/migration_verifier_test.go, internal/verifier/recheck.go, internal/verifier/recheck_test.go
Previously we stored the entire recheck queue in a single collection. This meant that, when we finished a generation, we had to “surgically” delete all rechecks for the old generation.
This changeset alters the metadata so that, rather than a storing rechecks in a single collection, we store them in generation-specific collections like `recheckQueue_gen0`, `recheckQueue_gen1`, etc. That way, when we want to clean out a prior generation’s recheck queue, we just drop a collection, which is much faster than deleting 100s of millions of individual recheck documents.
=> REP-5963 Migrate recheck queue to per-generation collections

internal/partitions/partitions.go
This contains 2 commits. The first removes literal min & max values, which are potentially-sensitive customer data, from logs. The second alters the logs in partitions.go to use structured logging rather than creating long messages with the data points. (The actual information is unchanged; it’ll just be more consistent with other messages added recently.)
The commits will be preserved, rather than being squashed, on merge.
=> Suppress min & max bounds from logs; clean up logging.

internal/partitions/partitions.go
This commit handles `SampleTooManyDuplicates` by reducing the number of partitions to 1/10 of the original value. It also reduces the number of documents to sample per partition from 10 to 3.
=> REP-5971 Reduce $sample cardinality

README.md, internal/util/bson.go, internal/util/bson_test.go, internal/verifier/migration_verifier.go, internal/verifier/recheck.go, internal/verifier/verification_task.go, main/migration_verifier.go
This allows users to set a custom maximum size for recheck tasks. The verifier observes this setting in 2 ways:
1. When creating recheck tasks, it will move onto the next task if the list of IDs has reached the maximum size.
2. When running recheck tasks, it splits the list of IDs into groups and runs each group separately (i.e., in series). This is so that, if a verification finishes generation 0 then hits problems in generation 1, the user can adjust the recheck size and have it take effect without restarting verification.
The reason for this change is that, as seen in HELP-73941, if the verifier sends many large queries to the server at once, it can deplete the server’s available memory, which can cause OOMs and elections. By throttling this new setting, customers can (hopefully) …
=> REP-5996 Allow users to reduce the max size of recheck tasks.

internal/verifier/compare.go, internal/verifier/compare_test.go, internal/verifier/migration_verifier.go, internal/verifier/migration_verifier_bench_test.go, internal/verifier/migration_verifier_test.go, internal/verifier/summary.go, internal/verifier/worker_tracker.go
This will make it easier to confirm, at a glance, that a given worker thread is still doing useful work.
Sample output:
```
Active worker threads (24 of 30):
+----------+---------------------+--------------------------+--------------+--------------------------+
| THREAD # |      NAMESPACE      |           TASK           | TIME ELAPSED |          DETAIL          |
+----------+---------------------+--------------------------+--------------+--------------------------+
|        0 | mmsdbjobs.data.jobs | 680a8636d968b0b72db5ae6f | 2m 12.05s    | read 228,176 documents   |
|        1 | mmsdbjobs.data.jobs | 680a8621d968b0b72db5ae20 | 19m 16.15s   | read 184,025 documents   |
|        2 | mmsdbjobs.data.jobs | 680a8626d968b0b72db5ae59 | 9m 23.05s    | read 319,682 documents   |
|        3 | …
```
=> REP-6000 Add a “Detail” column to the worker-thread table.

internal/partitions/partitions.go, internal/verifier/check.go, internal/verifier/migration_verifier.go, internal/verifier/migration_verifier_test.go, internal/verifier/web_server_test.go, internal/verifier/webserver.go, internal/verifier/webserver/binding_extjson.go, main/migration_verifier.go
Previously we parsed the document filter as plain JSON, which made it impossible to filter on ObjectID or other BSON-specific types.
This changeset fixes that by parsing the document filter as MongoDB’s extended JSON.
I’m going to merge the commits as-is rather than squashing. Note that there are two unrelated UX improvements here, as well as a fix for a race condition in an unrelated test, in discrete commits.
=> REP-5806 Parse document filter as extended JSON

mbson/bson_raw.go, mbson/unit_test.go
This fixes a small issue that arose in mongosync testing: if a document’s `_id` is BSON null—which can happen!—then the logic to chunk a slice of document `_id`s failed because apparently bson.MarshalValue() fails if given Go’s nil.
=> Fix ConvertToRawValue, which is necessary if _id is BSON null.

.github/workflows/release.yml, RELEASE.md
Annotated tags conveniently facilitate bundling release notes. This changes the build process to require an annotated tag.
=> Switch to annotated tags for releases

build.sh
This prevents problems when running migration-verifier on older OSes like Amazon Linux 2 (that remain in use).
=> Avoid CGO when building.

internal/verifier/compare.go, internal/verifier/migration_verifier_test.go, internal/verifier/statistics.go, internal/verifier/summary.go, internal/verifier/worker_tracker.go
Currently the non-debug logs offer no insight into currently-active tasks’ progress. So if tasks take a long time, non-debug logging will show now progress until one of those tasks finishes.
This amends logging thus:
- Document & byte tallies now incorporate in-progress tasks’ document & byte counts.
- “Active document comparison threads” is now printed.
- Each line of the “Namespaces in progress” table shows that namespace’s count of active threads.
=> REP-6438 Include currently-running task stats in baseline logs.

README.md, download_latest.sh
=> Add a script to download the latest version.

internal/verifier/migration_verifier_test.go, internal/verifier/statistics.go
Commit b4467f7a broke statistics computation when a recheck generation includes a collection-metadata task, e.g., if an index or collection attribute mismatches.
This fixes that by refining the aggregation logic. Tests are added to shore up this functionality.
=> Fix $size error in statistics computation.

main/migration_verifier.go
This fixes breakage introduced in commit 1f47e806.
=> Allow src & dst connection strings to be in config.yml.
